name: Github Pages
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: jontze/action-mdbook@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          use-mermaid: true
      - name: Show mdbook version
        run: mdbook --version
      - name: Show mermaid version
        run: mdbook-mermaid --version

      - uses: actions/checkout@v2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
